// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.js";
import * as Router from "next/router";

var PageComponent = {};

import { css } from "@linaria/core"
;

var examplesTitle = (css`
    font-weight: 700;
  `);

var Styles = {
  examplesTitle: examplesTitle
};

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var match = router.route;
  if (match === "/examples") {
    return React.createElement(MainLayout.make, {
                children: null
              }, React.createElement("h1", {
                    className: examplesTitle
                  }, "Examples Section"), React.createElement("div", undefined, content));
  } else {
    return React.createElement(MainLayout.make, {
                children: content
              });
  }
}

export {
  PageComponent ,
  Styles ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
