// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import { css } from "@linaria/core"
;

var title = (css`
      font-size: 1.875rem;
      line-height: 2.25rem;
      font-weight: 600;
    `);

var p = (css`
    margin-bottom: 0.5rem;
  `);

var subTitle = (css`
    font-size: 1.5rem;
    line-height: 2rem;
    font-weight: 600;
    margin-top: 1.25rem;
  `);

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: title
                }, "What is this about?"), React.createElement("p", {
                  className: p
                }, "This is a simple template for a Next\n      project using ReScript & linaria."), React.createElement("h2", {
                  className: subTitle
                }, "Quick Start"), React.createElement("pre", undefined, "git clone https://github.com/ryyppy/nextjs-default.git my-project\ncd my-project\nrm -rf .git"));
}

export {
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
