// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

import { css } from "@linaria/core"
;

var nav = (css`
      padding: 0.5rem;
      height: ${Styles.height}rem;
      display: flex;
      border-bottom-width: 1px;
      border-color: rgba(229, 231, 235, 1);
      justify-content: space-between;
      align-items: center;
      font-size: 0.875rem;
      line-height: 1.25rem;
    `);

var logo = (css`
    display: flex;
    align-items: center;
    width: 33.333333%;

    > img {
      width: 1.25rem;
    }

    > span {
      font-size: 1.25rem;
      line-height: 1.75rem;
      margin-left: 0.5rem;
      vertical-align: middle;
      font-weight: 600;

      > span {
        color: #9c4221;
      }
    }
  `);

var links = (css`
    display: flex;
    width: 66.666667%;
    justify-content: flex-end;

    > a {
      padding-left: 0.75rem;
      padding-right: 0.75rem;
    }

    > a:last-child {
      font-weight: 700;
    }
  `);

var container = (css`
    display: flex;
    min-width: 20rem;

    @media ${Styles.lg} {
      justify-content: center;
    }

    > div {
      max-width: 64rem;
      width: 100%;
      color: rgba(17, 24, 39, 1);
      font-weight: 400;

      @media ${Styles.lg} {
        width: 75%;
      }

      main {
        margin-top: 1rem;
        margin-left: 1rem;
        margin-right: 1rem;
      }
    }
  `);

var Styles_sm = "(min-width: 640px)";

var Styles_md = "(min-width: 768px)";

var Styles_lg = "(min-width: 1024px)";

var Styles_xl = "(min-width: 1280px)";

var Styles_xl2 = "(min-width: 1536px)";

var Styles = {
  sm: Styles_sm,
  md: Styles_md,
  lg: Styles_lg,
  xl: Styles_xl,
  xl2: Styles_xl2,
  height: 3,
  nav: nav,
  logo: logo,
  links: links,
  container: container
};

function MainLayout$Navigation(Props) {
  return React.createElement("nav", {
              className: nav
            }, React.createElement(Link, {
                  href: "/",
                  children: React.createElement("a", {
                        className: logo
                      }, React.createElement("img", {
                            src: "/static/zeit-black-triangle.svg"
                          }), React.createElement("span", undefined, "Next", React.createElement("span", undefined, "RE")))
                }), React.createElement("div", {
                  className: links
                }, React.createElement(Link, {
                      href: "/",
                      children: React.createElement("a", undefined, "Home")
                    }), React.createElement(Link, {
                      href: "/examples",
                      children: React.createElement("a", undefined, "Examples")
                    }), React.createElement("a", {
                      href: "https://github.com/tomvardasca/nextjs-default",
                      target: "_blank"
                    }, "Github")));
}

var Navigation = {
  make: MainLayout$Navigation
};

function MainLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: container
            }, React.createElement("div", undefined, React.createElement(MainLayout$Navigation, {}), React.createElement("main", undefined, children)));
}

var Link$1;

var make = MainLayout;

export {
  Link$1 as Link,
  Styles ,
  Navigation ,
  make ,
  
}
/*  Not a pure module */
